## 브로드캐스팅

In [1]:
from numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])
a + b

array([11, 11, 11])

In [2]:
from numpy import array

a = array([3, 4, 5, 7])
b = array([8, 7, 6])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### 스칼라의 브로드캐스팅

In [5]:
from numpy import array

a = array([3, 4, 5])
b = 2
a + b

array([5, 6, 7])

In [6]:
from numpy import array

A = array([[1, 2, 3], [1, 2 ,3]])
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

### 1차원 배열의 브로드캐스팅

In [8]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [10]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [11]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [12]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [14]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [15]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

### 1차원 배열과 2차원 배열의 동시 브로드캐스팅

In [16]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [18]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [19]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [20]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [21]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [22]:
y = arange(1, 3)
y

array([1, 2])

In [23]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [24]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

### 상수 np.newaxis 활용한 브로드캐스팅

In [37]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [38]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [39]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [40]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [41]:
b = array([1, 2, 3])
b

array([1, 2, 3])

In [42]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [43]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

## 고급 색인

In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 단순 색인 - 인덱싱과 슬라이싱

In [59]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [60]:
print([[2]])
print([[2, 3]])

[[2]]
[[2, 3]]


### 리스트 또는 ndarray로 인덱싱

In [61]:
x[[2, 3, 5, 8]] # 결과: ndarray

array([2, 3, 5, 8])

In [62]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [63]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

### 2차원 배열의 색인

In [64]:
x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [65]:
x[0, 1]

np.int64(1)

In [66]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [69]:
x[[0], [1]]

array([1])

In [70]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [71]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [72]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [75]:
x[[1, 3], [2, 2]]

array([10, 26])

In [76]:
x[[1, 3], [2]]

array([10, 26])

In [77]:
x[[1, 3], [3, 3]]

array([11, 27])

In [78]:
x[[1, 3], [3]]

array([11, 27])

In [87]:
x[array([0, 2, 4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [88]:
x[[[0], [2], [4]], [0, 1]] # 리스트 또는 ndarray로 인덱싱 할 때는 항상 브로드캐스팅을 생각해야 함

array([[ 0,  1],
       [16, 17],
       [32, 33]])

### 다양한 모양의 배열 색인

In [90]:
a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [91]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [92]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [93]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [94]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [95]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 04. 다차원 배열 결합과 분리

## np.vstack(tup)

### 2차원 배열 간의 vstack

In [3]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
c = np.arange(20, 24).reshape(2, 2)
c

array([[20, 21],
       [22, 23]])

In [7]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [8]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

### 2차원 배열과 1차원 배열의 vstack

In [9]:
d =  np.array([100, 200])
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [11]:
d = np.array([100, 200, 300])
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

### 1차원 배열 간의 vstack

In [16]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

## np.hstack(tup)

### 2차원 배열간의 hstack

In [17]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [12]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [13]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

### 1차원 배열 간의 hstack

In [20]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

## np.column_stack(tup)

### 2차원 배열 간의 column_stack

In [14]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [16]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [17]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [18]:
np.hstack((a,  b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

### 1차원 배열 간의 column_stack

In [20]:
x = np.array([1, 2, 3])
y = np.array([10 ,20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [21]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [22]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [23]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [24]:
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [25]:
np.column_stack == np.hstack

False

## np.row_stack(tup)

In [26]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
b = np.arange(10, 22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [30]:
np.row_stack((a, b))

C:\Users\User\AppData\Local\Temp\ipykernel_1676\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [31]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [32]:
a = np.array([4., 2., 1.])
b = np.array([3., 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


C:\Users\User\AppData\Local\Temp\ipykernel_1676\1077890801.py:3: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((a, b)))


In [33]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [35]:
np.row_stack == np.vstack

False

## np.concatenate(tup)

### 다차원 배열이 보유한 축 0으로 합치기

In [37]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.concatenate((a, b, c), axis=0)

array([1, 2, 3, 4, 5, 6])

In [39]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6])

In [40]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [45]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [44]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [46]:
np.concatenate((x, y, z))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

### 다차원 배열이 보유한 축 1로 합치기

In [47]:
np.concatenate((x, y), axis=1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [48]:
np.concatenate((x, y, z), axis=1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [50]:
np.concatenate((x, y), axis=None) # 평면화

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

## np.stack(tup)

### 다차원 배열을 특정 축으로 확장(np.newaxis)하여 그 축으로 합치기

In [51]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [52]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [53]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
np.stack((a, b), axis=-1) # (3,) -> (3, 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [62]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [73]:
ax0 = np.stack((x, y, z), axis=0) # (2, 3) -> (1, 2, 3)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [74]:
ax0.shape

(3, 2, 3)

In [75]:
ax1 = np.stack((x, y, z), axis=1) # (2, 3) -> (2, 1, 3)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [77]:
ax1.shape

(2, 3, 3)

In [78]:
ax2 = np.stack((x, y, z), axis=2) # (2, 3) -> (2, 3, 1)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [79]:
ax2.shape

(2, 3, 3)

In [80]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [81]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [82]:
np.expand_dims(x, axis=2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [83]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [84]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [85]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [90]:
np.expand_dims(z, axis=2) # [:, :, np.newaxis]와 동일

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [91]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

## 배열의 결합 비교

### hstack과 column_stack 비교

In [92]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [93]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [94]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [95]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [96]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [97]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [98]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

### vstack과 row_stack 비교

In [99]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [101]:
np.row_stack((a, b))

C:\Users\User\AppData\Local\Temp\ipykernel_1676\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [102]:
np.vstack((a, b))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

### np.c_[]와 np.column_stack

In [103]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [104]:
np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [105]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [108]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [109]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [110]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [116]:
np.c_[x, 10, 20, y] # np.column_stack의 단축

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [115]:
np.column_stack((x, 10, 20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

## np.r_[]

### row_stack과 같지 않음

In [148]:
import numpy as np

a = np.array([1, 2 ,3])
b = np.array([4, 5, 6])

In [149]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

### row_stack과 비슷하지만 축을 확장 시키지 않음

In [150]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [151]:
np.row_stack((a, b))

C:\Users\User\AppData\Local\Temp\ipykernel_1676\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

### arange 단축

In [154]:
np.r_[3:10:3, [0] * 2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [155]:
print([0] * 2)
np.array([0]) * 2

[0, 0]


array([0])

### linspace 단축

In [156]:
np.r_[-1:1:6j, [0] * 2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [157]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

In [158]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [159]:
np.r_[a, a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [160]:
np.row_stack((a, a, a))

C:\Users\User\AppData\Local\Temp\ipykernel_1676\3993545990.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, a, a))


array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

### 결합이 2차원의 0축으로 고정된 row_stack과는 다르게 축을 지정

In [181]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [179]:
print(np.hstack((np.array([1, 2]), np.array([3, 4])))) # 1차원 0(-1)축
print(np.hstack((np.array([[1, 2]]), np.array([[3, 4]])))) # 2차원 1(-1)축

[1 2 3 4]
[[1 3]
 [2 4]]


In [174]:
print(np.row_stack((np.array([1, 2]), np.array([3, 4]))))
print(np.row_stack((np.array([[1, 2]]), np.array([[3, 4]]))))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


C:\Users\User\AppData\Local\Temp\ipykernel_1676\1684229019.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((np.array([1, 2]), np.array([3, 4]))))
C:\Users\User\AppData\Local\Temp\ipykernel_1676\1684229019.py:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((np.array([[1, 2]]), np.array([[3, 4]]))))


In [177]:
print(np.vstack((np.array([1, 2]), np.array([3, 4]))))
print(np.vstack((np.array([[1, 2]]), np.array([[3, 4]]))))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [175]:
print(np.column_stack((np.array([1, 2]), np.array([3, 4]))))
print(np.column_stack((np.array([[1, 2]]), np.array([[3, 4]]))))

[[1 3]
 [2 4]]
[[1 2 3 4]]


In [176]:
print(np.c_[(np.array([1, 2]), np.array([3, 4]))])
print(np.c_[((np.array([[1, 2]]), np.array([[3, 4]])))])

[[1 3]
 [2 4]]
[[1 2 3 4]]


In [182]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [184]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [193]:
np.r_['0, 2', [1, 2, 3], [4, 5, 6]] # 기본적으로 바깥(-1)으로 확장 stack에서는 바깥이 0

array([[1, 2, 3],
       [4, 5, 6]])

In [187]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [191]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]] # 0은 (3, 1, 1)로 확장 stack이랑 다름

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [194]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [195]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

## 1차원 배열의 결합

In [196]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [197]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [198]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [199]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [200]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
np.row_stack((a, b))

C:\Users\User\AppData\Local\Temp\ipykernel_1676\2094407319.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [203]:
np.r_['0, 2',a, b]

array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [210]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [214]:
np.r_['-1, 2, 0', a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [215]:
np.concatenate((a[:, np.newaxis], b[:, np.newaxis]), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])