## 브로드캐스팅

In [1]:
from numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])
a + b

array([11, 11, 11])

In [2]:
from numpy import array

a = array([3, 4, 5, 7])
b = array([8, 7, 6])
a + b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### 스칼라의 브로드캐스팅

In [5]:
from numpy import array

a = array([3, 4, 5])
b = 2
a + b

array([5, 6, 7])

In [6]:
from numpy import array

A = array([[1, 2, 3], [1, 2 ,3]])
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

### 1차원 배열의 브로드캐스팅

In [8]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [10]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [11]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [12]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [14]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [15]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

### 1차원 배열과 2차원 배열의 동시 브로드캐스팅

In [16]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [18]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [19]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [20]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [21]:
from numpy import arange

x = arange(0, 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [22]:
y = arange(1, 3)
y

array([1, 2])

In [23]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [24]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

### 상수 np.newaxis 활용한 브로드캐스팅

In [37]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [38]:
a = x[None, :]
a

array([[ 0, 10, 20, 30]])

In [39]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [40]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [41]:
b = array([1, 2, 3])
b

array([1, 2, 3])

In [42]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [43]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

## 고급 색인

In [58]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 단순 색인 - 인덱싱과 슬라이싱

In [59]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [60]:
print([[2]])
print([[2, 3]])

[[2]]
[[2, 3]]


### 리스트 또는 ndarray로 인덱싱

In [61]:
x[[2, 3, 5, 8]] # 결과: ndarray

array([2, 3, 5, 8])

In [62]:
x[np.array([5, 3, -4, 8])]

array([5, 3, 6, 8])

In [63]:
x[np.array([10])]

IndexError: index 10 is out of bounds for axis 0 with size 10

### 2차원 배열의 색인

In [64]:
x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [65]:
x[0, 1]

np.int64(1)

In [66]:
x[:, 2:8]

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [69]:
x[[0], [1]]

array([1])

In [70]:
x[:, [5, 4]]

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [71]:
x[[1, 3]]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [72]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [75]:
x[[1, 3], [2, 2]]

array([10, 26])

In [76]:
x[[1, 3], [2]]

array([10, 26])

In [77]:
x[[1, 3], [3, 3]]

array([11, 27])

In [78]:
x[[1, 3], [3]]

array([11, 27])

In [87]:
x[array([0, 2, 4]), array([0, 1])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [88]:
x[[[0], [2], [4]], [0, 1]] # 리스트 또는 ndarray로 인덱싱 할 때는 항상 브로드캐스팅을 생각해야 함

array([[ 0,  1],
       [16, 17],
       [32, 33]])

### 다양한 모양의 배열 색인

In [90]:
a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [91]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [92]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [93]:
a[arange(2, 4)][:, [1, 0]]

array([[17, 16],
       [25, 24]])

In [94]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [95]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

## 04. 다차원 배열 결합과 분리

In [13]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

### numpy.hstack()

In [17]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [20]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

### numpy.column_stack()

In [21]:
x = np.array([1, 2, 3])
y = np.array([10 ,20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [28]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
y = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
np.column_stack((x, y))

array([[[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8],
        [5, 6],
        [7, 8]]])

In [31]:
np.r_[-1:1:6j, [0] * 2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])