In [1]:
import numpy as np
np.__version__

'1.26.4'

In [8]:
from numpy import arange
x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [6]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [12]:
type(x + y)

numpy.ndarray

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

## 04. 다차원 배열 결합과 분리

In [13]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
np.vstack((a, b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y))

array([[1, 2, 3],
       [5, 6, 7]])

### numpy.hstack()

In [17]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [19]:
np.hstack((a, b))

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [20]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

### numpy.column_stack()

In [21]:
x = np.array([1, 2, 3])
y = np.array([10 ,20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [28]:
x = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
y = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
np.column_stack((x, y))

array([[[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8],
        [5, 6],
        [7, 8]]])

In [31]:
np.r_[-1:1:6j, [0] * 2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])